routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::middleware(['auth'])->prefix('administracion')->group( function(){
    Route::resource("usuario", "admin\UserController");
    Route::resource("permisos", "admin\PermissionController")->only('index');
    Route::resource("roles", "admin\RoleController");

    Route::resource("mascotas", "MascotaController");
    Route::get('mascotas/eliminarimagen/{id}', 'MascotaController@eliminarimagen')->name('mascotas/eliminarimagen');
});

app/Models/Mascota.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mascota extends Model
{
    use HasFactory;

    protected $table = 'mascotas';

    protected $fillable  = [
        "Id",
        "Nombre",
        "edad",
        "tiempo",
        "animal",
        "tel",
        "Imagenes",
        "DescripMedica",
    ];

    // Relación One to Many (Uno a muchos), un registro puede tener muchas imágenes
    public function imagenesMascotas()
    {
        return $this->hasMany('App\Models\imgMascotas');
    }
}

app/Http/Controllers/MascotaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Mascota;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\imgMascotas;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests\Mascotas\EditRequest;
use App\Http\Requests\Mascotas\CreateRequest;

class MascotaController extends Controller
{
    const PERMISSIONS = [
        'create' => 'mascota.create',
        'edit' => 'mascota.edit',
        'destroy' => 'mascota.destroy',
        // '' => '',
    ];

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role_or_permission:SuperAdmin|' . self::PERMISSIONS['create'])->only(['create', 'store']);
        $this->middleware('role_or_permission:SuperAdmin|' . self::PERMISSIONS['edit'])->only(['edit', 'update', 'eliminarimagen']);
        $this->middleware('role_or_permission:SuperAdmin|' . self::PERMISSIONS['destroy'])->only(['destroy']);
    }

    public function index()
    {
        if(Auth::user()->rol == 'usuario'){
            return redirect()->route("home");
        }
        $mascotas = Mascota::paginate(10);
        return view("admin.mascotas.index", compact('mascotas'));
    }

    public function create()
    {
        return view('admin.mascotas.create');
    }

    public function store(CreateRequest $request)
    {
        $mascota = new Mascota();
        $mascota->Nombre = $request->Nombre;
        $mascota->edad = $request->edad;
        $mascota->tiempo = $request->tiempo;
        $mascota->animal = $request->animal;
        $mascota->tel = $request->tel;
        $mascota->DescripMedica = $request->DescripMedica;
        $mascota->Imagenes = date('dmyHi');
        echo $mascota;
        $mascota->save();

        $image = $request->file('img');
        if(!empty($image)){

            foreach($request->file('img') as $image)
            {
                $imagen = uniqid() . $image->getClientOriginalName();
                $formato = $image->getClientOriginalExtension();
                $image->move(public_path().'/uploads/mascotas/', $imagen);

                // Guardamos el nombre de la imagen en la tabla 'img_bicicletas'
                DB::table('img_mascota')->insert(
                    [
                        'nombre' => $imagen,
                        'formato' => $formato,
                        'mascota_id' => $mascota->id,
                        'created_at' => date("Y-m-d H:i:s"),
                        'updated_at' => date("Y-m-d H:i:s")
                    ]
                );
            }
        }

        return redirect()->route("mascotas.index")->with('success', 'Nueva mascota agregada correctamente');
    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $mascota = Mascota::findOrFail($id);
        $imagenes = imgMascotas::where('mascota_id', '=', $id)->get();
        return view('admin.mascotas.edit', compact('imagenes'), ['mascota'=> $mascota]);
    }

    public function update(EditRequest $request, $id)
    {
        $mascota = Mascota::findOrFail($id);
        $mascota->update($request->all());
        // Actualizar imagenes
        $ci = $request->file('img');

        // Si la variable '$ci' no esta vacia, actualizamos el registro con las nuevas imágenes
        if(!empty($ci)){

            // Recibimos una o varias imágenes y las actualizamos
            foreach($request->file('img') as $image)
                {
                    $imagen = uniqid() . $image->getClientOriginalName();
                    $formato = $image->getClientOriginalExtension();
                    $image->move(public_path().'/uploads/mascotas/', $imagen);

                    // Actualizamos el nuevo nombre de la(s) imagen(es) en la tabla 'img_bicicletas'
                    DB::table('img_mascota')->insert(
                        [
                            'nombre' => $imagen,
                            'formato' => $formato,
                            'mascota_id' => $mascota->id,
                            'created_at' => date("Y-m-d H:i:s"),
                            'updated_at' => date("Y-m-d H:i:s")
                        ]
                    );
                }
        }
        return redirect()->route("mascotas.index")->with('success', 'Informacion de la mascota actualizada correctamente');
    }

    public function destroy($id)
    {
        $mascota = Mascota::findOrFail($id);

        // Selecciono las imágenes a eliminar
        $imagen = DB::table('img_mascota')->where('mascota_id', '=', $id)->get();
        $imgfrm = $imagen->implode('nombre', ',');

        // Creamos una lista con los nombres de las imágenes separadas por coma
        $imagenes = explode(",", $imgfrm);

        // Recorremos la lista de imágenes separadas por coma
        foreach($imagenes as $image){

            // Elimino la(s) imagen(es) de la carpeta 'uploads'
            $dirimgs = public_path().'/uploads/mascotas/'.$image;

            // Verificamos si la(s) imagen(es) existe(n) y procedemos a eliminar
            if(File::exists($dirimgs)) {
                File::delete($dirimgs);
            }

        }
        $mascota->imagenesMascotas()->delete();
        $mascota->delete();
        return redirect()->route("mascotas.index")->with('success', 'Eliminado correctamente');

    }

    // Eliminar imagen de un Registro
    public function eliminarimagen($id)
    {
        // Elimino la imagen de la carpeta 'uploads'
        $imagen = imgMascotas::select('nombre')->where('id', '=', $id)->get();
        $imgfrm = $imagen->implode('nombre', ',');

        $mascota = imgMascotas::select('mascota_id')->where('id', '=', $id)->get();
        $idP = $mascota->implode('mascota_id', ',');
        // Elimino la(s) imagen(es) de la carpeta 'uploads'
        $dirimgs = public_path().'/uploads/mascotas/'.$imgfrm;

        // Verificamos si la(s) imagen(es) existe(n) y procedemos a eliminar
        if(File::exists($dirimgs)) {
            File::delete($dirimgs);
        }
        imgMascotas::destroy($id);

        return Redirect::to('administracion/mascotas/'.$idP.'/edit');

    }
}

resources/views/admin/mascotas/create.blade.php
@extends('layouts.main', ['activePage' => 'plantas', 'titlePage' => 'Agregar Mascota'])

@section('css')
    <link href="{{ asset('/css/previewIMG.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                    <form action="{{route("mascotas.store")}}" method="post" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-tittle">Nueva Mascota</h4>
                            <p class="card-category">Ingresar Datos</p>
                        </div>

                        <div class="card-body">
                            @include('admin.mascotas.form')
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/previewIMG.js') }}"></script>
@endsection

resources/views/admin/mascotas/edit.blade.php
@extends('layouts.main', ['activePage' => 'plantas', 'titlePage' => 'Editar Mascota'])

@section('css')
    <link href="{{ asset('/css/previewIMG.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form action="{{ route('mascotas.update', $mascota->id) }}" method="post" class="form-horizontal" enctype="multipart/form-data">

                    @csrf
                    @method('PUT')
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-tittle">Mascota</h4>
                            <p class="card-category">Editar informacion de la mascota seleccionada</p>
                        </div>

                        <div class="card-body">
                            @include('admin.mascotas.form')
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                    </div>
                </form>
                {{-- Imagenes de la planta --}}
                <div class="card">
                    <div class="card-header card-header-success">
                        <h4 class="card-tittle">Imagenes</h4>
                        <p class="card-category">Si desea eliminar una imagen haga clic en la X</p>
                    </div>
                    <div class="card-body">
                        <div>
                            @if ( !empty ( $mascota->Imagenes) )
                                <span>Imagen(es) Actual(es): </span>
                                <br>

                                <!-- Mensaje: Imagen Eliminada Satisfactoriamente ! -->
                                @if(Session::has('message'))
                                    <div class="alert alert-primary" role="alert">
                                        {{ Session::get('message') }}
                                    </div>
                                @endif

                                <!-- Mostramos todas las imágenes pertenecientesa a este registro -->
                                <div class="row">
                                    @foreach($imagenes as $img)
                                        <div class=" col-md-4">
                                            <img src="../../../uploads/mascotas/{{ $img->nombre }}" width="200" class="img-fluid">

                                            <!-- Botón para Eliminar la Imagen individualmente -->
                                            <a href="{{ route('mascotas/eliminarimagen', [$img->id]) }}" class="close"
                                                onclick="return confirm('¿Esta seguro de eliminar esta imagen?');" >
                                                <span aria-hidden="true">&times;</span>
                                            </a>
                                        </div>
                                    @endforeach
                                </div>
                           @else
                                Aún no se ha cargado una imagen para este producto
                           @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    <script src="{{ asset('js/previewIMG.js') }}"></script>
@endsection

resources/views/admin/mascotas/form.blade.php
{{-- Formulario Para el Edit --}}
@if ( !empty ( $mascota->id) )
    <div class="row">
        <div class="form-group col-md-3">
            <label for="animal">Especie:</label>
            <input type="text" name="animal" class="form-control" placeholder="Ingrese la especie..." autofocus required value="{{ old('animal', $mascota->animal) }}">
            @if ($errors->has('animal'))
                <span class="error text-danger" for="input-animal">{{ $errors->first('animal') }}</span>
            @endif
        </div>

        <div class="form-group col-md-3">
            <label for="Nombre">Nombre:</label>
            <input type="text" name="Nombre" class="form-control" placeholder="Ingrese el nombre..." autofocus required value="{{ old('Nombre', $mascota->Nombre) }}">
            @if ($errors->has('Nombre'))
                <span class="error text-danger" for="input-Nombre">{{ $errors->first('Nombre') }}</span>
            @endif
        </div>

        <div class="form-group col-md-1">
            <label for="edad">Edad:</label>
            <input type="number" name="edad" class="form-control" placeholder="Años de la mascota" required value="{{ old('edad', $mascota->edad) }}">
            @if ($errors->has('edad'))
                <span class="error text-danger" for="input-edad">{{ $errors->first('edad') }}</span>
            @endif
        </div>

        <div class="form-group col-md-2">
            <label>tiempo</label>
            <select class="form-control" name="tiempo">
            <option value="Meses">Meses</option>
            <option value="Años">Años</option>
            </select>
            @if ($errors->has('tiempo'))
                <span class="error text-danger" for="input-tiempo">{{ $errors->first('tiempo') }}</span>
            @endif
        </div>
        <div class="form-group col-md-3">
            <label for="tel">Contacto:</label>
            <input type="tel" name="tel" class="form-control" placeholder="Numero de Telefono" required value="{{ old('tel', $mascota->tel) }}">
            @if ($errors->has('tel'))
                <span class="error text-danger" for="input-tel">{{ $errors->first('tel') }}</span>
            @endif
        </div>
    </div>

    <div class="form-group ">
        <label for="DescripMedica">Descripcion:</label>
        <textarea rows="6" class="form-control" placeholder="Es de color..." name="DescripMedica" required>{{ old('DescripMedica', $mascota->DescripMedica) }}</textarea>
        @if ($errors->has('DescripMedica'))
            <span class="error text-danger" for="input-DescripMedica">{{ $errors->first('DescripMedica') }}</span>
        @endif
    </div>
@else
{{-- Formulario Para el Create --}}

<div class="row">
        <div class="form-group col-md-3">
            <label for="animal">Especie:</label>
            <input type="text" name="animal" class="form-control" placeholder="Ingrese la especie..." autofocus required value="{{ old('animal') }}">
            @if ($errors->has('animal'))
                <span class="error text-danger" for="input-animal">{{ $errors->first('animal') }}</span>
            @endif
        </div>

        <div class="form-group col-md-3">
            <label for="Nombre">Nombre:</label>
            <input type="text" name="Nombre" class="form-control" placeholder="Ingrese el nombre..." autofocus required value="{{ old('Nombre') }}">
            @if ($errors->has('Nombre'))
                <span class="error text-danger" for="input-Nombre">{{ $errors->first('Nombre') }}</span>
            @endif
        </div>

        <div class="form-group col-md-1">
            <label for="edad">Edad:</label>
            <input type="number" name="edad" class="form-control" placeholder="Años de la mascota" required value="{{ old('edad') }}">
            @if ($errors->has('edad'))
                <span class="error text-danger" for="input-edad">{{ $errors->first('edad') }}</span>
            @endif
        </div>

        <div class="form-group col-md-2">
            <label>tiempo</label>
            <select class="form-control" name="tiempo">
            <option value="Meses">Meses</option>
            <option value="Años">Años</option>
            </select>
            @if ($errors->has('tiempo'))
                <span class="error text-danger" for="input-tiempo">{{ $errors->first('tiempo') }}</span>
            @endif
        </div>

        <div class="form-group col-md-3">
            <label for="tel">Contacto:</label>
            <input type="tel" name="tel" class="form-control" placeholder="Numero de Telefono" required value="{{ old('tel') }}">
            @if ($errors->has('tel'))
                <span class="error text-danger" for="input-tel">{{ $errors->first('tel') }}</span>
            @endif
        </div>
    </div>

    <div class="form-group ">
        <label for="DescripMedica">Descripcion:</label>
        <textarea rows="6" class="form-control" placeholder="Es de color..." name="DescripMedica" required>{{ old('DescripMedica')}}</textarea>
        @if ($errors->has('DescripMedica'))
            <span class="error text-danger" for="input-DescripMedica">{{ $errors->first('DescripMedica') }}</span>
        @endif
    </div>
@endif

<input name="img[]" type="file" id="file" multiple="multiple">
@if ($errors->has('img.*'))
    <br><br>
    <span class="error text-danger" for="input-Descripcion">{{ $errors->first('img.*') }}</span>
@endif
@if ($errors->has('img'))
    <br><br>
    <span class="error text-danger" for="input-Descripcion">{{ $errors->first('img') }}</span>
@endif


<div id="container-input">
    <div class="wrap-file">
        <div id="preview-images"></div>
    </div>
</div>

resources/views/admin/mascotas/index.blade.php
@extends('layouts.main', ['activePage' => 'plantas', 'titlePage' => 'Listado de Mascotas'])
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card-header-primary">
                                <h4 class="card-tittle">Mascotas</h4>
                                <p class="card-category">Mascotas que estan en adopcion</p>
                            </div>

                            <div class="card-body">
                                @if (session('success'))
                                    <div class="alert alert-success" role="success">
                                        {{ session('success')}}

                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                @endif
                                <div class="row">
                                    <div class="col-12 text-right">
                                        <a href="{{route("mascotas.create")}}" class="btn btn-sm btn-success">Agregar nueva mascota</a>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class="text-primary">
                                            <th>Especie</th>
                                            <th>Nombre</th>
                                            <th>Edad</th>
                                            <th>Tel</th>
                                            <th>Descripcion</th>
                                            <th class="text-right">Acciones</th>
                                        </thead>
                                        <tbody>
                                            @foreach ($mascotas as $mascota)
                                            <tr>
                                                <td>{{$mascota->animal}}</td>
                                                <td>{{$mascota->Nombre}}</td>
                                                <td>{{$mascota->edad}} {{$mascota->tiempo}}</td>
                                                <td>{{$mascota->tel}}</td>
                                                <td>{{$mascota->DescripMedica}}</td>
                                                <td class="td-actions text-right">
                                                    <a href="{{route("mascotas.edit", $mascota->id)}}" class="btn btn-warning" title="Editar" rel="tooltip">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    <form action="{{route("mascotas.destroy", $mascota->id)}}" method="post" style="display: inline-block;" onsubmit="return confirm('¿Esta seguro de eliminar esta mascota?')">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger" type="submit" title="Eliminar" rel="tooltip">
                                                            <i class="material-icons">close</i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="card-footter ml-auto">
                                {{ $mascotas->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/material-kit.js?v=2.0.5') }}" type="text/javascript"></script>
@endsection